<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?=$this->baseUrl()?>">News</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<?=$this->baseUrl()?>">Home</a></li>
      <li><a href="<?=$this->baseUrl()?>/news/">Add Rss</a></li>
    </ul>
  </div>
</nav>


<h1>RSS feeds</h1>
<?php
    foreach ($this->news as $item) {
    echo "<h3>". $item->title()."</h3>" ;
    echo "<hr>";
    echo $item->description();
    echo "<hr>";
    
}